require:
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
